version: '3.1'
services:
  db:
    image: postgres:16.2-alpine
    container_name: db-postgresql-prueba
    restart: unless-stopped
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: PRUEBA
      POSTGRES_PASSWORD: PRUEBA
    ports:
      - "5435:5432"